[project]
name = "octavius"
version = "0.1.0"
requires-python = ">=3.9"
# opcional: dependencias en runtime
# dependencies = ["pyaudio", "numpy"]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"